//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadorinator.ServiceContract {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CadorinatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadorinatorResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadorinator.ServiceContract.CadorinatorResources", typeof(CadorinatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a exit.
        /// </summary>
        internal static string CommandName_Exit_Command {
            get {
                return ResourceManager.GetString("CommandName_Exit_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close safely the console.
        /// </summary>
        internal static string CommandName_Exit_Description {
            get {
                return ResourceManager.GetString("CommandName_Exit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a help.
        /// </summary>
        internal static string CommandName_Help_Command {
            get {
                return ResourceManager.GetString("CommandName_Help_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List all commands.
        /// </summary>
        internal static string CommandName_Help_Description {
            get {
                return ResourceManager.GetString("CommandName_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a listFilm.
        /// </summary>
        internal static string CommandName_ListFilm_Command {
            get {
                return ResourceManager.GetString("CommandName_ListFilm_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LIst all film with relative internal id.
        /// </summary>
        internal static string CommandName_ListFilm_Description {
            get {
                return ResourceManager.GetString("CommandName_ListFilm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a since.
        /// </summary>
        internal static string CommandName_ListFilm_Param_since {
            get {
                return ResourceManager.GetString("CommandName_ListFilm_Param_since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a publishReport.
        /// </summary>
        internal static string CommandName_PublishReport_Command {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immediatly publish a report.
        /// </summary>
        internal static string CommandName_PublishReport_Description {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cityId.
        /// </summary>
        internal static string CommandName_PublishReport_Param_cityId {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Param_cityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a filmId.
        /// </summary>
        internal static string CommandName_PublishReport_Param_filmId {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Param_filmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a from.
        /// </summary>
        internal static string CommandName_PublishReport_Param_from {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Param_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a mode.
        /// </summary>
        internal static string CommandName_PublishReport_Param_mode {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Param_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a to.
        /// </summary>
        internal static string CommandName_PublishReport_Param_to {
            get {
                return ResourceManager.GetString("CommandName_PublishReport_Param_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a restart.
        /// </summary>
        internal static string CommandName_Restart_Command {
            get {
                return ResourceManager.GetString("CommandName_Restart_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restart the background application, if already closed, it will start it.
        /// </summary>
        internal static string CommandName_Restart_Description {
            get {
                return ResourceManager.GetString("CommandName_Restart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a waitTime.
        /// </summary>
        internal static string CommandName_Restart_Param_waitTime {
            get {
                return ResourceManager.GetString("CommandName_Restart_Param_waitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a setBackupFrequency.
        /// </summary>
        internal static string CommandName_SetBackupFrequency_Command {
            get {
                return ResourceManager.GetString("CommandName_SetBackupFrequency_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the time between backups.
        /// </summary>
        internal static string CommandName_SetBackupFrequency_Description {
            get {
                return ResourceManager.GetString("CommandName_SetBackupFrequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a dayOfTheWeek.
        /// </summary>
        internal static string CommandName_SetBackupFrequency_Param_dayOfTheWeek {
            get {
                return ResourceManager.GetString("CommandName_SetBackupFrequency_Param_dayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a timeOfTheDay.
        /// </summary>
        internal static string CommandName_SetBackupFrequency_Param_timeOfTheDay {
            get {
                return ResourceManager.GetString("CommandName_SetBackupFrequency_Param_timeOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a setDelay.
        /// </summary>
        internal static string CommandName_SetDelay_Command {
            get {
                return ResourceManager.GetString("CommandName_SetDelay_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [DEBUG] Set the delay time between the HTTP requests.
        /// </summary>
        internal static string CommandName_SetDelay_Description {
            get {
                return ResourceManager.GetString("CommandName_SetDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a delayTime.
        /// </summary>
        internal static string CommandName_SetDelay_Param_delayTime {
            get {
                return ResourceManager.GetString("CommandName_SetDelay_Param_delayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a setGoogleDriveToken.
        /// </summary>
        internal static string CommandName_SetGoogleDriveToken_Command {
            get {
                return ResourceManager.GetString("CommandName_SetGoogleDriveToken_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the google token used to access the drive folder. Remember to activate the drive accessability.
        /// </summary>
        internal static string CommandName_SetGoogleDriveToken_Description {
            get {
                return ResourceManager.GetString("CommandName_SetGoogleDriveToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a token.
        /// </summary>
        internal static string CommandName_SetGoogleDriveToken_Param_token {
            get {
                return ResourceManager.GetString("CommandName_SetGoogleDriveToken_Param_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the samples time collection before the film start.
        /// </summary>
        internal static string CommandName_SetSampleRange_Description {
            get {
                return ResourceManager.GetString("CommandName_SetSampleRange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a sampleRange.
        /// </summary>
        internal static string CommandName_SetSampleRange_Param_delayTime {
            get {
                return ResourceManager.GetString("CommandName_SetSampleRange_Param_delayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a setSampleRange.
        /// </summary>
        internal static string CommandName_SetSamplesRange_Command {
            get {
                return ResourceManager.GetString("CommandName_SetSamplesRange_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a toogleBackup.
        /// </summary>
        internal static string CommandName_ToogleBackup_Command {
            get {
                return ResourceManager.GetString("CommandName_ToogleBackup_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle the backup feature.
        /// </summary>
        internal static string CommandName_ToogleBackup_Description {
            get {
                return ResourceManager.GetString("CommandName_ToogleBackup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a togleRemotePublish.
        /// </summary>
        internal static string CommandName_ToogleRemotePublish_Command {
            get {
                return ResourceManager.GetString("CommandName_ToogleRemotePublish_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle the publicatons to the remote repository for reports and backups.
        /// </summary>
        internal static string CommandName_ToogleRemotePublish_Description {
            get {
                return ResourceManager.GetString("CommandName_ToogleRemotePublish_Description", resourceCulture);
            }
        }
    }
}
